### PR TITLE
AR Goggles

### PR DESCRIPTION
**Pull request by Olfi01**
As suggested in #58 (by me), I implemented the AR goggles.

I'd be happy to provide documentation for the lua methods, too, I just don't know where I'd put that.

This makes the mod dependent on Curios, but I would consider that a worthwile tradeoff, even more so since Curios is already part of most modpacks.

### CODE REVIEW

**Comment by Wojbie** [comment]
Why not make Curios optional dependency? Would that be possible? Make it act as helmet if Curios is not installed.

Or skip it all together and make googles work from anywhere in player inventory?

**Comment by Seniorendi** [comment]
I completely agree to what Wojbie means.
And could you send a text to the player when they link the AR goggles?

**Comment by Olfi01** [comment]
@Wojbie @Seniorendi 
Curios as an optional dependency doesn't work the way it is implemented right now, since I am using a few convenience methods offered by it. I suppose it would be possible to refactor the code in a way to make curios optional, but I would have to look into that later today or tomorrow.
As for the text when linking the AR goggles, sure, I will add that as well.

**Comment by Olfi01** [comment]
Do NOT merge yet, still needs one fix

**Comment by UnhappyCodings** [comment]
It would be cool if you could use colorcodes as &l / §l for thick or &o / §o for italic letters also an in-string color changing for example with the layout: "{\0xffffff}Hello {\0x000000}Goodbye"

**Pull request merged**
