### PR TITLE
Chunky Turtle Logic Rework

### LINKED ISSUE #557: Chunks loaded by chunky turtles are not loaded upon reloading the world
### Describe

When a chunky turtle moves out of render distance and is the only thing loading itself, reloading the world will not re-load the turtle.

### Steps to reproduce

1. Place a chunky chatty turtle outside of the spawn-chunks.
2. Insert into `startup.lua`:
```lua
local chatBox = peripheral.find("chatBox",peripheral.wrap)
while true do
chatBox.sendMessage("hi")
end
```
3. Leave the chunks so the turtle is out of render distance
4. Reload the world

The turtle will no longer spam the chat, and only reactivate when loaded by external means.

### Multiplayer?

No

### Version

1.18.2-0.7.31r (Latest 1.18.2)

### Minecraft, Forge and maybe other related mods versions

Forge 40.2.8 Minecraft 1.18.2

### Screenshots or Videos

_No response_

### Crashlog/log

_No response_

### PR DESCRIPTION
**Pull request by zyxkad**
**PLEASE READ THE [GUIDELINES](https://github.com/SirEndii/AdvancedPeripherals/blob/1.20.1/CONTRIBUTING.md) BEFORE MAKING A CONTRIBUTION**

As guideline said, the 1.19.2 version is at #582 (just sync the patches in this PR)

* **Please check if the PR fulfills these requirements**
- [x] The commit message are well described
- [ ] Docs have been added / updated (for features or maybe bugs which were noted). If not, please update the needed documentation [here](https://github.com/SirEndii/Advanced-Peripherals-Documentation/pulls). This is not mandatory
- [x] All changes have fully been tested

* **What kind of change does this PR introduce?** (Bug fix, feature, ...)

Fix chunky turtle's behaviour.

* **What is the current behavior?** (You can also link to an open issue here)

Now the chunky turtle sometimes will not works, especially after server restart.

* ~~**What is the new behavior (if this is a feature change)?**~~

* **Does this PR introduce a breaking change?** (What changes might users need to make in their scripts due to this PR?)

If some player made their structure depends on the unstable chunk loading, then it will be a breaking change.

* **Other information**:

### Needs to test

- [x] Chunk will be forced when turtle is actived.
- [x] Chunk will be forced when turtle enter chunk border.
- [x] Chunk will unforce after remove turtle / turtle exit the chunk.
- [x] Chunk will unforce when turtle left chunk border.
- [x] Chunk will unforce when time expired.
- [x] Chunks will be saved after server stopped.
- [x] Chunks will be loaded after server started.
- [x] Test to break the turtle, and put it back in another chunk before cleanup.
- [x] Test with larger radius.
- [x] Test change radius from small to large.
- [x] Test change radius from large to small.
- [x] Test `/advancedperipherals forceload` and its subcommands
- [ ] Test on pure server.
- [ ] Maybe more ...

### CODE REVIEW

**Comment by zyxkad** [comment]
@SirEndii This PR is ready for further review, however, changes were not fully tested yet. I'll do more test when I get time.

### Needs to test

*\<List moved to the top\>*

**Comment by zyxkad** [comment]
@SirEndii Do you think add a subcommand `/advancedperipherals forceload` will be a good idea? because I found out the vanilla `/forceload` will not show the chunks loaded by chunky turtles, `/computercraft dump` will show all computers but not only chunky turtle.

If we add this command, server owner can keep track on what's using their resources.

**Comment by SirEndii** [comment]
> @SirEndii Do you think add a subcommand `/advancedperipherals forceload` will be a good idea? because I found out the vanilla `/forceload` will not show the chunks loaded by chunky turtles, `/computercraft dump` will show all computers but not only chunky turtle.
> 
> If we add this command, server owner can keep track on what's using their resources.

Yeah
That sounds like a good idea

**Comment by zyxkad** [comment]
@SirEndii All of the tests I can think of are done, except test on pure server. I don't think it's really necessary, but will try if I got more time. ;)

**Comment by SirEndii** [comment]
Thank you for the PR(s)!
The new chunk system looks good, I will address the deprecated functions when I finish the port to 1.20.4

**Pull request merged**
