### PR TITLE
Merge dev/1.19.2 into dev/1.20.1

### LINKED ISSUE #43: Up/down versions of automata block methods
### Describe your idea

Turtles/automata cannot turn vertically, but this is not a big problem, as they can fly upwards or downwards in any rotation. The issue is, though, that they cannot INTERACT with blocks above or below them without a separate command. In CC:Tweaked proper, there are three versions of each block interaction command: one for the block the turtle is facing, one for the block above the turtle, and one for the block below the turtle. See [here](https://tweaked.cc/module/turtle.html#v:digDown) for how there are, for example, dig(), digUp() and digDown() commands.
The commands do the exact same thing as the base command, but instead of targeting the block the turtle is facing, they target the block immediately above and below the turtle, regardless of which direction it is facing. Automata do not have this option for the lookAtBlock, digBlock, or useOnBlock methods.

### Describe alternatives you've considered if you've any

You CAN go backwards and then upwards/downwards to access the block, but there is not always room to do this. Plus it wastes a little bit of fuel.

### Additional context

To be clear, I'm not asking for turtles to be able to turn vertically, just a couple of methods that use the base method on the blocks y+1 and y-1 of the turtle.

### Linked Issues

_No response_

### LINKED ISSUE #67: Add `slot` info for `inventoryManager.getItemInHand`
### Describe your idea

As the title, return the slot that the player selecting, then we could easily figure out which slot should we operate for the player in some specific case (e.g. put the current handing item into the chest).

### Describe alternatives you've considered if you've any

invoke both `getItems()` and `getPlayerHand()`, compare items name, count and nbt then we can get a slow and inaccurate response.

### Additional context

_No response_

### Linked Issues

_No response_

### LINKED ISSUE #419: Automata Core do not use turtle's heading as fake player's direction
### Describe

When using the `.digBlock()` function of the Automata core it doesn't break blocks from the side that the turtle would be interacting with. As an example this is a problem when using tools that dig 3x3 or 5x5 areas.

It should also be noted that the `.digBlock()` function has one extra reach when it breaks blocks which is inconsistant with vanilla ComputerCraft `.dig()` where the block has to be against the turtle's nose.

### Steps to reproduce

1. Make turtle.
2. Equip Automata Core.
3. Give a hammer that digs larger sizes.
4. `lua`
5. `auto = peripheral.wrap("left")`
6. `auto.digBlock()`

### Multiplayer?

No

### Version

1.18.2-0.7.23r

### Minecraft, Forge and maybe other related mods versions

Minecraft 1.18.2 - Forge 40.1.92

### Screenshots or Videos

https://clips.twitch.tv/VastZanyAardvarkNinjaGrumpy-GOCZDA493yvF-eLB

### Crashlog/log

_No response_

### LINKED ISSUE #427: ME Bridge Deletes NBT Data on exportItem(item: table, direction: string) -> number, err: string
### Describe

Using the following code to move items, the me bridge deletes nbt data.

As a note, I have tried from a directly connected dire/chest to a sub-netted drive/chest both cause this issue.

**NOT ONLY BOOKS**

Will delete the data off apotheosis items ect.

``` lua
local DEBUG = true
local LOGGING = false

-- Helper
function string:contains(sub)
    return self:find(sub, 1, true) ~= nil
end

function string:count(value)
    local t = self.gsub(self, ("[^%s]"):format(value), "")
    if DEBUG then print(("\t\t\t(\"%s\"):count(\"%s\") = %d"):format(self, value, #t)) end
    return #t
end

function table.contains(tbl, value)
    -- For single depth tables that only contain strings
    if tbl ~= nil then
        for _, v in pairs(tbl) do
            if string.find(v, value) then return true end
        end
    end

    return false
end

function table.print(tbl)
    for k, v in pairs(tbl) do
        print(("%s: %s"):format(k, v))
    end

    return false
end

-- Overrides
local _print = print
print = function(...) if DEBUG then _print(...) end end

local label = "ME-EXPORTER"
os.setComputerLabel(label)

-- Connect to me system
local me = peripheral.find("meBridge")

-- Conenction to storage from ME Bridge
local dir_to_chest = "up"

local accepted_items = {
    "minecraft:enchanted_book"
}

local tags = {
    -- "forge:armor",
    -- "forge:tools"
    "forge:books"
}

local taboo_items = {
    "Elytra"
}

-- Function to determine if should run main
local span = 10  -- Time in ms to wait to run

function FormatItem(tag, item)
    if DEBUG then print(("Name: %s\n\tNBT: "):format(tag)); table.print(item.nbt) read(); end
    item.nbt = {}
    return item
end

function ExportItem(tag, item)
    local num, err
    local itemToMove = FormatItem(tag, item)

    if DEBUG then 
        print(("\n\n----------\nItem: %s\n\tCount: %s\n\tNBT: %s\n----------\n\n"):format(itemToMove.name, itemToMove.count, itemToMove.nbt))
        print("Press Enter to Accept Item Move")
        read()
    end

    num, err = me.exportItem(itemToMove, dir_to_chest)

    return num, err
end

function ExamineInventory()
    local me_inv = me.listItems()
    for i=1, #me_inv do
        local item = me_inv[i]
        if item == nil then do break end end

        -- if DEBUG then
        --     for k, v in pairs(item) do
        --         print(("%s\t\t%s"):format(k, v))
        --     end
        --     read()
        -- end

        for _, tag in pairs(tags) do
            if table.contains(item.tags, tag) then
                if DEBUG then table.print(item.tags) end
                if table.contains(accepted_items, item.name) then
                    ExportItem(tag, item)
                    do break end
                end
            end
        end
    end
end

function Main()
    _print(("Attempting to run inventory managment will sleep for %d after"):format(span))
    ExamineInventory()

    sleep(span)

    Main()  -- Main loop
end

parallel.waitForAny(Main, function()
	os.pullEventRaw("terminate")
end)

```

Version is 
AdvancedPeripherals-0.7.25r.jar
cc-tweaked-1.19.2-1.101.2.jar
AE2WTLib-12.8.5.jar
AEAdditions-1.19.2-4.0.3.jar
appliedenergistics2-forge-12.9.2.jar
megacells-forge-2.0.0-beta.7-1.19.2.jar

### Steps to reproduce

Using the above code.

1. Create a enchanted book
2. Have an empty ae2 system
3. Place enchanted book in the ae2 network, main or sub network connected to me bridge
4. Run management code
5. Watch it delete nbt data off what ever is filtered for

Looked at some closed issues
#416
#424 

Both seem related but alas I have not looked at the respective code in this repository as I was baffled by the nbt data just going poof.

Also as an aside, the configuration for the device is a cc advanced computer on the bottom, then the bridge then a barrel on top

So,
```json
[' B ',
 ' M ',
 ' C '
]
B = minecraft:barrel
M = advancedperipherials:me_bridge
C = computercraft:computer_advanced
```

Did try in other configurations but this is what I was using when I encountered the issue.

### Multiplayer?

Yes

### Version

1.19.2-0.7.24b (Latest 1.19.2)

### Minecraft, Forge and maybe other related mods versions

43.2.6

### Screenshots or Videos

_No response_

### Crashlog/log

_No response_

### LINKED ISSUE #587: Slot indices are 0-based instead of 1-based
### Describe

Slot filter arguments start at index 0 instead of 1. Lua indices are 1-based, so it makes it difficult to write code that interoperates with the peripheral API.

Indices should be 1-based to be consistent with Lua and CC:T standards.

### Steps to reproduce

image

1. Connect an ME Bridge and vanilla chest to a wired network
2. Create an ME system with item storage and connect it to the ME Bridge
3. Place items in the first and second slots of the chest
4. Run the following code;
```lua
local chestName = "left"
local chest = peripheral.wrap(chestName)
local bridge = peripheral.wrap("right")
for slot in pairs(chest.list()) 
  bridge.importItemFromPeripheral({fromSlot=slot},chestName)) 
end
```
## Expected Results
All items are moved from the chest into the ME system

## Actual Results
Slot 0 still contains the original item

## Workaround
Reduce the indices sent to the ME Bridge by 1

### Multiplayer?

Yes

### Version

1.19.2-0.7.34r (Latest 1.19.2)

### Minecraft, Forge and maybe other related mods versions

1.19.2 / Skies Expert

### Screenshots or Videos

_No response_

### Crashlog/log

_No response_

### LINKED ISSUE #592: scanEntities(range) table missing health fields
### Describe

Some passive mobs like chicken, sheep, horse, cow (may be more), Do not have health and maxHealth fields in the table that function scanEntities(range) returns.

### Steps to reproduce

1. Connect "environmentDetector" to a computer
2. Summon some passive creatures (chickens, sheep, ...)
3. Call scanEntities(range) from the detector
4. Look through the returned table

```lua
local scanner = peripheral.wrap("environmentDetector_0")
local SEARCH_RADIUS = 128

file_handler = io.open("out", "w")
io.output(file_handler)
for _, entity in pairs(scanner.scanEntities(SEARCH_RADIUS)) do
    for field, value in pairs(entity) do
        if (field == "name" or field == "health") then
            io.write(field .. " : " .. tostring(value) .. "\n")
        end
    end
    io.write("-----\n")
end
io.close(file_handler)
```
изображение

### Multiplayer?

No

### Version

1.19.2-0.7.34r (Latest 1.19.2)

### Minecraft, Forge and maybe other related mods versions

Froge - 43.3.8; MC - 1.19.2

### Screenshots or Videos

_No response_

### Crashlog/log

_No response_

### LINKED ISSUE #599: Impossible to craft compass turtle
### Describe

Hi ! I see "compass turtle" in JEI but i'm unable to craft it with a turtle and a compass... Is it a bug or something else ? Thanks for your anwser !

Magrets

### Steps to reproduce

Take a turtle, take a compass et try to craft both together or with " turtle.equipLeft()" it says "not a valid upgrade"

### Multiplayer?

No

### Version

1.20.1-0.7.38r

### Minecraft, Forge and maybe other related mods versions

Forge  47.2.21| Minecraft 1.20.1

### Screenshots or Videos

_No response_

### Crashlog/log

_No response_

### LINKED ISSUE #603: Note block does not trigger allay
### Describe

Playing note on note block by using it as peripheral does not trigger allays.

### Steps to reproduce

1. Place computer
2. Place note block right next to it
3. Summon allay and give it random item to collect
4. Play noteblock

### Multiplayer?

Yes

### Version

1.20.1-0.7.39r (Latest 1.20.1)

### Minecraft, Forge and maybe other related mods versions

47.2.30 on Minecraft 1.20.1

### Screenshots or Videos

_No response_

### Crashlog/log

_No response_

### LINKED ISSUE #623: Chat Box allows sending of chat messages with negative range
### Describe

When using the `sendMessage` (and similar) functions of the Chat Box, a range can be set with a parameter. During the creation of tests for #562 I noticed two issues with this:

- When a `chatBoxMaxRange` is set in the config, one can simply pass -1 as a range to the`sendMessage` function and thus bypass the max range set in the config
- When `chatBoxMaxRange` is set to -1 (default), passing a negative integer smaller than -1 as a range to the`sendMessage` function results in no message sent

### Steps to reproduce

1. Place a Computer and a Chat Box side by side
2. In the Lua console of the computer, execute the following script `peripheral.find("chatBox").sendMessage("Message with short range", "GameTest", "<>", "&a", -1)` (or `peripheral.find("chatBox").sendMessage("Message with short range", "GameTest", "<>", "&a", -2)`)

### Multiplayer?

No

### Version

Own compiled build.

### Minecraft, Forge and maybe other related mods versions

Forge 43.3.13 Minecraft 1.19.2

### Screenshots or Videos

_No response_

### Crashlog/log

_No response_

### PR DESCRIPTION
**Pull request by zyxkad**
- Goodbye stinky
- [#250]Added Fluid Detector
- No Energy
- Added the gas detector
- Fixed detectors not saving max flow rate
- Fixed `getTransferRate()` - gas detector
- [#320] Added the basics of a distance detector Checking the distance does work for the upper direction of the block The key elements are mising - Height mode - Mode for transparent blocks - Mode for entities - Laser visibility - direction of the block
- Added `getRadiation` to the environment detector
- 1.19.3 for 0.8
- Adapt me and rs bridge functions. Both bridges now have the same functions with the same names. This makes it easier to support both in the same script Still needs some adjustments and documentation
- Some distance detector stuff
- Some distance detection work, added the ability to also scan for entities
- Laser pew pew
- Remove deprecation of IInventoryBlock.java
- Update some dependencies
- Run on selfhosted
- Some very very basic smart glasses approaches. This just adds the smart glasses as item and the computer with a terminal behind it. A custom API and a `flat.lua` file in the rom do exist too
- Checked the style
- Re-add the smart glasses model
- Away with you
- Add a new memory card texture with a bounded property
- Added an inventory and an item handler for the glasses
- Added a smart glasses interface
- [#423] Fixed that some functions of the me and rs bridge ignore or increasing the count they want to export
- tidy
- Refactored the screens into the client package Added a debug to the server worker
- Some UI stuff
- Added a new taiga village structure
- Finished the UI. Added a modules and peripheral tab with proper visualization. Added the ability to add peripherals to the glasses which also get added to the glasses computer
- First thoughts about the module system
- Added modules in the form of items, every item which is a module implements IModuleItem which contains a method for the actual IModel. The IModel then contains a tick method and a method for the name of the module. To implement lua functions into that module, we create a class which implements IModuleFunctions which then contains the methods annotated with the LuaFunction annotation The modules can be accessed by the peripheral on the back of the glasses. Because of that, I removed the back slot of the peripheral slots. Modules and peripherals are now indexed when the inventory updates and not every tick
- Remove old ar controller block and peripheral
- Some distance detector progress
- [#320] Finished the distance detector. Everything seems to work fine, the only thing I want to add is an event.
- Add some documentation and satisfy checkstyle
- 🧹
- Fixed detection type
- Load ap addons statically Return an itemstack created from the AEItemKey instead of a new itemstack to fix #427
- Fixed some compiling issues
- More context please
- Unify the rs and me bridge methods by using an interface. Adds more functions and makes the ME and RS Bridge work the same
- Do the same for the rs bridge.
- I'm casting away
- Port 0.8 pack to 1.19.2 since we do not support 1.19.3 anymore.
- Adapt to checkstyle rules
- Woopsy
- Do some safety checks to satisfy sonar
- Fix creative tab Satisfy checkstyle
- Fixing a bug which I made by mistake
- Minor bug fixes and improvements for the smart glasses system
- Fix some compiling and checkstyle issues. We still have some issues and bugs, not nothing too annoying
- Refactor imports, improve comment clarity and fix that `APAddons` wasn't initialized
- Remove `DEV` from the version since our pipeline does handle this automatically
- Change the loading of our APAddons class to static loading since the older variation was called too late which led to not functioning features
- Check the style
- copy cat
- Runned datagen
- Fixed that peripherals remain in the glasses computer after removing them
- Cleanups, docs and a ui fix
- Fixed smartglasses smithing recipe
- Prototype for an object bases rendering system. Currently working on the server side of things
- Implemented mapping functionality via reflections.
- Starting to use annotations for our properties to improve safety. This is currently not a clean way, but I need to sync the project to another device...
- Improve the way how we map the arguments retrieved from the lua endpoint to the fields of our class. We're now using an annotation based system to further improve security and implement optional range limits needed for some values.
- swoosh
- Trying a way to sync the overlay objects to the client of a player. Actual synchronisation isn't implemented, this is just a prototype
- Move to snake_case peripheral names to better fit with CC:T's standards
- Remove our `to/fromPeripheral` functions and add the logic for peripheral based storages directly to the `impport` and `export` functions Needs to be documented
- Don't check dependency licenses
- Fixed the colony integrator
- Add missing applied mekanistics to the build.gradle
- Start to implement more of the RS Bridge and ME Bridge IStorageSystemPeripheral functions. Also started adding better pattern support for both. WIP commit, commited due to device change
- Implement pattern filtering for the me bridge
- Fixed pattern listing. AE2 does not offer a way to get all patterns of the system. To solve this, we probe over all connected nodes in the system and check if they have patterns. This is adapted from the PatternAccessTerminal which does the same
- Improve and extend the functionality of the ME Bridge by implementing the handling of external fluid and item storage. This includes the capability to get the total, used, and available external storage for both fluid and item elements.
- Implement mekanism chemical integration to the ME Bridge
- Some cleanup
- [#539] Remove the external storage counters from the internal functions
- Add Drives and Cells support to the ME Bridge
- use the BasicCellInventory class instead of trying to get the information we need out of the item tag. Add a `usedBytes` and `totalBytes` field to the drive's object
- [#51] Start an implementation for `getCraftingTasks` and `cancelCraftingTasks`
- Set lua function to use the main tread.
- Add peripheral functions for the Dim Chest of the Dimensional Storage mod. Also add Jade for better testing purposes.
- Implement prototype of `cancelCraftingTasks` to the ME Bridge
- [#13] Add a hotkey module
- [AP-Features-13](https://github.com/IntelligenceModding/Advanced-Peripherals-Features/issues/13) Fixed hotkey module not working on servers
- Fixed the smart glasses ui when playing on servers
- Add the ability for the modules to inventory tick and fix double queued `glassesKeyPressed` event
- `!`
- Add a night vision module to the smart glasses Add a `onUnequipped` function to the IModule interface Switch to a slot based module system to better track module changes
- Adapt me functions to the internal api changes
- Satisfy checkstyle
- add advanced place method to the compass peripheral
- costs fuel when tring to use compass to place in far distance
- add wall operation
- rename argument wall -> anchor
- fix stylecheck
- use nil instead of false
- use validateSide instaed of Direction.byName
- call livingEntityToLua but not entityToLua when serializing animal fix #592
- Implement `cancelCraftingTasks` for the ME Bridge
- add pitch & yaw argument to automata core close IntelligenceModding/Advanced-Peripherals-Features#43 fix #419
- add player.doActionWithRot instead of writing ton of overload methods
- fix java generic
- fix missing imports
- remove unused import
- accept NBTed items as turtle upgrade fix #599
- add slot field to inventoryManager.getItemInHand close IntelligenceModding/Advanced-Peripherals-Features#67
- make inventoryManager.getItem return nil instead of empty table
- change slot index starts from 1 fix #587
- add UnsafeConfig for ignore NBT
- fix null pointer
- fix automata core will place two blocks at a time
- remove unused imports
- move place method from compass to automataBlockHandPlugin
- add comment for placeBlock method
- add static keyword for internal class
- remove extra empty lines
- fix typo forward -> front
- make the directions makes more sense
- fix playNote will not trigger alley fix #603
- fix playNote will not trigger alley fix #603
- Revert "Merge branch 'dev/0.8' into dev/1.19.2"
- Skip the calculation of storage busses without any connected storage block
- lost -> lose, behaviour -> behavior (American English)
- Fixed `isOnEnchantedSoil()` for the mana flower integration
- Satisfy checkstyle
- fix player can bypass the maximum chatbox range by setting a negative message range fix #623
- fix playerdetector bypass range issue
- forgot to remove a Math.min
- fix README link and missing semicolon
- fix version changes

**PLEASE READ THE [GUIDELINES](https://github.com/SirEndii/AdvancedPeripherals/blob/dev/1.20.1/CONTRIBUTING.md) BEFORE MAKING A CONTRIBUTION**

* **Please check if the PR fulfills these requirements**
- [x] The commit message are well described
- [ ] All changes have fully been tested

### CODE REVIEW

**Comment by zyxkad** [comment]
horrible 187 commits included dev/0.8 because of my last mis-merge which is reverted :(

**Comment by SirEndii** [comment]
> horrible 187 commits included dev/0.8 because of my last mis-merge which is reverted :(

Also my fault because I didn't see that ;D

**Comment by SirEndii** [comment]
In general, I agree, linking the issues with a PR. But we follow the convention that we only close the issues after we released a fix for it. Or else, they're not fixed in production

**Comment by zyxkad** [comment]
> In general, I agree, linking the issues with a PR. But we follow the convention that we only close the issues after we released a fix for it. Or else, they're not fixed in production

Ah ye, you know github will automatically close issue when something commited to the default branch

**Pull request merged**
