### PR TITLE
Added optional arguments to specify crafting cpu to use.

### LINKED ISSUE #401: ME Bridge choose crafting cpu
### Describe your idea

The `craftItem` method should have another parameter to choose crafting cpu.
I didn’t find any information in the documentation, so I opened a Feature Request.

### Describe alternatives you've considered if you've any

_No response_

### Additional context

_No response_

### Linked Issues

_No response_

### PR DESCRIPTION
**Pull request by michele-grifa**
I have added an optional arguments to `craftItem` and `isItemCrafting`, to specify crafting cpu to use.

### CODE REVIEW

**Comment by SirEndii** [comment]
Looking good, but you would need to satisfy the checkstyle

**Comment by michele-grifa** [comment]
I changed the style, but the check fails on RedstoneIntegrator style, but i didn't touch it.

**Comment by SirEndii** [comment]
> I changed the style, but the check fails on RedstoneIntegrator style, but i didn't touch it.

I see, my fault

**Comment by SirEndii** [comment]
Thank you for the contribution!

**Pull request merged**
