### PR TITLE
Add zh_cn items and manual translation

### PR DESCRIPTION
**Pull request by HfSrJun**
the home page for the manual is also translated, but it seems that there's no multi-language version for it, so I didn't upload it.

### CODE REVIEW

**Comment by SirEndii** [comment]
Heyo,
if you want to contribute to the translations of Advanced Peripherals, please do that via [Crowdin](https://crowdin.com/project/advanced-peripherals/zh-CN)

But thank you anyways for trying to help Advanced Peripherals!

**Comment by zyxkad** [comment]
@SirEndii 
Actually the translation for zh_cn is already done there, but I don't know how to submit. <https://crowdin.com/translate/advanced-peripherals/44/enus-zhcn?filter=basic&value=3>

**Comment by SirEndii** [comment]
That's indeed a good question.
That should happen automatically, but somehow the syncing is dead. I'll fix this for 1.18 in the next days and then switch crowdin to 1.19 translations

**Comment by SirEndii** [comment]
fixed
uploaded via crowdin and merged #475 
Will be in game in the next release

**Pull request closed without merging**
