### PR TITLE
Update RefinedStorage.java to fix the Bug reportet in #497

### LINKED ISSUE #497: Refined System Overflow problem
### Describe

When Refined storage is used in combination with drawers from Functional Storage the external storage can get so big that the number overflows.

### Steps to reproduce

Playing FTB Stoneblock 3 1.7.1 Downloaded with the FTB App (I couldn't figure out what version of your mod is used :/ )

Place RS controller and connect a drawer with 4 netherite upgrades as external Storage
Place Computer with rsBridge inbetween next to the controller

read the max external storage as such:
```Lua
local rsb = peripheral.find("rsBridge")
amount = rsb.getMaxItemExternalStorage()
print(amount)
```

output: 2,147,483,647

now add a second drawer without any upgrades

when i execute the script again the number overflows and becomes negative

Let me know if you need more information or if i need to create a bug report somewhere else 
~Luna <3

### Multiplayer?

Yes

### Version

1.18.2-0.7.30r (Latest 1.18.2)

### Minecraft, Forge and maybe other related mods versions

FTB StoneBlock 3 1.7.1

### Screenshots or Videos

_No response_

### Crashlog/log

_No response_

### PR DESCRIPTION
**Pull request by LunaLorea**
fixes #497  Overflow Bug for Refined Storage

Changed these four methodes to use the long type instead of int
 - getMaxItemDiskStorage
 - getMaxFluidDiskStorage
 - getMaxItemExternalStorage
 - getMaxFluidExternalStorage

I havent built it to test the change since I honestly dont know how Oo

### CODE REVIEW

**Comment by zyxkad** [comment]
> I havent built it to test the change since I honestly dont know how Oo

Always test before creating pr is a good habit :)

**Comment by SirEndii** [comment]
Yeah, we also generally don't accept PRs which aren't fully tested

You can test this by running `gradle build` to build a .jar file, or you can use `gradle runClient` to start a client

If you just have the project locally, you can run `./gradlew build` or `./gradlew runClient` in a command prompt while in the folder

**Comment by SirEndii** [comment]
The checks passed, so gradle should be able to build the jar without issues

**Comment by LunaLorea** [comment]
Will test it and get back to u

**Comment by SirEndii** [comment]
If you need more help with contributing, you can read our [guideline](https://github.com/SirEndii/AdvancedPeripherals/blob/1.20.1/CONTRIBUTING.md#contributing-to-advanced-peripherals)

**Pull request closed without merging**
