### PR TITLE
Added inventory manager nbt support

### LINKED ISSUE #317: InventoryManager add/remove with NBT data
### Describe your idea

Currently the InventoryManager's `addItemToPlayer` and `removeItemFromPlayer` function's item argument does not support NBT tags, thus we cannot add/remove enchanted items or rockets for example.  
It would be nice to:
- Add new functions, as to not change the existing API, or
- Change the functions' signature to instead take a table, like the RS/ME bridges' `exportItem`

### Describe alternatives you've considered if you've any

One alternative is to export from the  RS/ME system to an empty chest, and don't filter while using the InventoryManager

### Additional context

I think the second option is better even tho it changes API, because it would unify the ME and RS bridges and the InventoryManager

### Linked Issues

_No response_

### PR DESCRIPTION
**Pull request by Erv00**
Added two functions to work with nbt, closes #317 
The old functions are unchanged, the new ones work the same, but support nbt tags.

### CODE REVIEW

**Comment by SirEndii** [comment]
I'll review this when I get back home in a week

**Comment by SirEndii** [comment]
Looking good - I don't see any issues so far

**Comment by SirEndii** [comment]
Would you want to add this to the ap documentation? https://github.com/Seniorendi/Advanced-Peripherals-Documentation

**Comment by Erv00** [comment]
Yes, I'll do it soon

**Pull request merged**
