### PR TITLE
[draft] Allow Inventory Manager to list, pull, and push to player Curios slots

### LINKED ISSUE #8: Curios compatibility for the Inventory Manager
### Describe your idea

Is it possible to add inventory slots created by Curios to the Inventory Manager API?

### Describe alternatives you've considered if you've any

_No response_

### Additional context

Curios allows other mods to create additional player inventory slots. As of now (1.18), items in these slots are invisible/inaccessible to the Inventory Manager.

### Linked Issues

_No response_

### PR DESCRIPTION
**Pull request by Kurtoid**
closes SirEndii/Advanced-Peripherals-Features#8

### CODE REVIEW

**Comment by SirEndii** [comment]
One thing I noticed is, that you don't check if curios is loaded since it's a optional dependency

So if curios is not loaded, the game would crash when someone runs these functions

**Comment by SirEndii** [comment]
And ignore the failed github action, these currently do not work for pull requests

**Comment by SirEdvin** [comment]
I can suggest reusing peripheral plugin logic as [environmental sensor](https://github.com/SirEndii/AdvancedPeripherals/blob/d2e2f6b646ea03c007c93badfa6a0d4a5608185d/src/main/java/de/srendi/advancedperipherals/common/addons/mekanism/EnvironmentRadiationPlugin.java#L7) do.

**Comment by Kurtoid** [comment]
> One thing I noticed is, that you don't check if curios is loaded since it's a optional dependency

Would implementing this as a plugin handle that? I'll give it a try

**Comment by Kurtoid** [comment]
Making sure I understand correctly: I should move the Curios calls to a new class in `common/addons/curios/`, create a `PERIPHERAL_PLUGINS` like in the Environmental Sensor, and define and use `InventoryManagerPeripheral.addIntegrationPlugin` ?

Edit: wait, BasePeripheral has `addPlugin` - should I use that, or only call `addPlugin` at initialization like the Environmental Sensor? For now, I'll follow what the Environmental Sensor does as recommended by SirEdvin

**Comment by Kurtoid** [comment]
Just encountered this: https://github.com/TheIllusiveC4/Curios/issues/238
so this might not even be possible unless there's a workaround

**Comment by SirEndii** [comment]
> Just encountered this: [TheIllusiveC4/Curios#238](https://github.com/TheIllusiveC4/Curios/issues/238) so this might not even be possible unless there's a workaround

Oh indeed, that's a issue

A workaround would be that we check the items before adding them

**Comment by SirEndii** [comment]
> Edit: wait, BasePeripheral has `addPlugin` - should I use that, or only call `addPlugin` at initialization like the Environmental Sensor? For now, I'll follow what the Environmental Sensor does as recommended by SirEdvin

Yeah, do it like edvin recommended it

**Comment by SirEndii** [comment]
Any progress? I don't want to put you under pressure or give you time pressure
I'm just asking because I'll release an update soon and want to know if I'll include your changes or not

**Comment by Kurtoid** [comment]
I don't think I'll have it ready soon - academics kicked back up. I have an
idea on how to filter it, but making everything stable and all will take
time

**Comment by SirEndii** [comment]
Alright, no problem
And thank you for the quick response

**Comment by SirEndii** [comment]
Greetings @Kurtoid 
Do you have any plans to work on this?

**Comment by Kurtoid** [comment]
Whoops, I took a break from minecraft and forgot about this. It looks like Curios now has the support needed to do this without workarounds (https://github.com/TheIllusiveC4/Curios/issues/238#issuecomment-1705847407). I'm not sure if I can do it in a timely manner, though

**Comment by SirEndii** [comment]
Greetings
I will close this for now
If anyone wants to implement this, feel free to just leave a message or create a new PR

**Pull request closed without merging**
