### PR TITLE
1.19.2 Powah Reactor Integration

### PR DESCRIPTION
**Pull request by neoroutine**
Basic third-party integration for Powah Reactors. Querying status, fuel, carbon, redstone, temperature, current energy and max energy is now possible.

### CODE REVIEW

**Comment by SirEndii** [comment]
Ignore the failed github actions
Everything important worked

**Comment by neoroutine** [comment]
Ok thanks for the heads up, wondered if I missed something.

**Comment by SirEndii** [comment]
Mark this pr as a draft if you still make changes to it. So I don't merge an unfinished PR by accident

**Comment by neoroutine** [comment]
Done, thanks !

**Comment by SirEndii** [comment]
👍🏻

**Comment by SirEndii** [comment]
Thank you.
I'll look into that when I get the time.

If you want, you can add proper documentation to it → https://github.com/SirEndii/Advanced-Peripherals-Documentation
You wouldn't need to add the pictures - that's something I can do

**Comment by neoroutine** [comment]
Please take your time.
Of course, I added some basic documentation, feel free to edit it (Opened a PR on the repo).
Thanks again for being so helpful.

**Review by SirEndii — APPROVED** [review]
Looks good to me - I'll merge this after some tests

**Pull request merged**
