### PR TITLE
fix player can bypass the maximum chatbox/playerdetector range by setting a negative range

### LINKED ISSUE #623: Chat Box allows sending of chat messages with negative range
### Describe

When using the `sendMessage` (and similar) functions of the Chat Box, a range can be set with a parameter. During the creation of tests for #562 I noticed two issues with this:

- When a `chatBoxMaxRange` is set in the config, one can simply pass -1 as a range to the`sendMessage` function and thus bypass the max range set in the config
- When `chatBoxMaxRange` is set to -1 (default), passing a negative integer smaller than -1 as a range to the`sendMessage` function results in no message sent

### Steps to reproduce

1. Place a Computer and a Chat Box side by side
2. In the Lua console of the computer, execute the following script `peripheral.find("chatBox").sendMessage("Message with short range", "GameTest", "<>", "&a", -1)` (or `peripheral.find("chatBox").sendMessage("Message with short range", "GameTest", "<>", "&a", -2)`)

### Multiplayer?

No

### Version

Own compiled build.

### Minecraft, Forge and maybe other related mods versions

Forge 43.3.13 Minecraft 1.19.2

### Screenshots or Videos

_No response_

### Crashlog/log

_No response_

### PR DESCRIPTION
**Pull request by zyxkad**
**PLEASE READ THE [GUIDELINES](https://github.com/SirEndii/AdvancedPeripherals/blob/dev/1.20.1/CONTRIBUTING.md) BEFORE MAKING A CONTRIBUTION**

* **Please check if the PR fulfills these requirements**
- [x] The commit message are well described
- [x] All changes have fully been tested

* **What kind of change does this PR introduce?** (Bug fix, feature, ...)
  Bug fix

* **What is the current behavior?** (You can also link to an open issue here)
  - #623

* **Does this PR introduce a breaking change?** (What changes might users need to make in their scripts due to this PR?)
  No

### CODE REVIEW

**Review by SirEndii — APPROVED** [review]
LGTM

**Comment by SirEndii** [comment]
Didn't see that this is a draft on my phone
Woops

**Comment by zyxkad** [comment]
Yeah player detector has same issue, fixing rn

**Review by SirEndii — APPROVED** [review]
LGTM!

**Pull request merged**
