### PR TITLE
Added playerJoin, playerLeave, playerChangedDimension events on Playe…

### PR DESCRIPTION
**Pull request by michele-grifa**
…r Detector

Based on SirEndii/Advanced-Peripherals-Features#10

### CODE REVIEW

**Comment by SirEdvin** [comment]
I just want to add, that this effectively register every peripheral and don't de-register them on detach. I am not sure if Forge will handle it correctly ... 

Probably it is better to use approach from [Events](https://github.com/SirEndii/AdvancedPeripherals/blob/1.19.3/src/main/java/de/srendi/advancedperipherals/common/events/Events.java)

**Comment by michele-grifa** [comment]
Yes but if i use that approach, the methods must be static and so I don't have access to the current peripheral.

**Comment by SirEdvin** [comment]
Yes, and in [ChatBox](https://github.com/SirEndii/AdvancedPeripherals/blob/1.19.3/src/main/java/de/srendi/advancedperipherals/common/blocks/blockentities/ChatBoxEntity.java) you subscribe to this message queue and read it every tick. 
And from block entity you have access to peripheral.

**Comment by michele-grifa** [comment]
I used the Events approach, now should be better.

The example for the docs are:
Player Join Event
```lua
local event, playerName, dimension = os.pullEvent('playerJoin')
```

Player Leave Event
```lua
local event, playerName, dimension = os.pullEvent('playerLeave')
```

Player Changed Dimension Event
```lua
local event, playerName, fromDim, toDim = os.pullEvent('playerChangedDimension')
```

**Comment by SirEndii** [comment]
Thank you!

**Pull request merged**
